local shell = require("shell")
local args = shell.parse(...)

local event = require("event")
local component = require("component")
local internet = require("internet")
local tunnel = component.tunnel
local handle = internet.open("wb://127.0.0.1:5500//robotws")
local data = handle:read(10)
print(data)
handle:write("1234")
handle:close()
print("done connecting")
tunnel.send(args[1], args[2])
local name, from, to, maxdistance, distance, message = event.pull("modem")
print(message)